

                09Welcome to Pandemia Installer!07
0a
                          .-=-.          .--.
              __        .'     '.       /  " )
      _     .'  '.     /   .-.   \     /  .-'0c\0a
     ( \   / .-.  \   /   /   \   \   /  /    0c^0a
      \ `-` /   \  `-'   /     \   `-`  /
       `-.-`     '.____.'       `.____.'  07by 0cRossonet
07

Inserisci il modello di sistema che intendi installare:
( 0aSe con si seleziona niente, dopo 60 secondi, parte
       CentOS5.x - Nodo Pandemia con <op> VNC locale07 ) 

0clocale07 - CentOS5.x - Nodo Pandemia con <op>
0cvnc07 - CentOS5.x - Nodo Pandemia con <op> VNC locale
0ccripto07 - CentOS5.x - Nodo Pandemia con <op> ( crypto fs )
0cnoop07 - CentOS5.x - Nodo Pandemia senza <op>
0cnoopvnc07 - CentOS5.x - Nodo Pandemia senza <op> VNC locale
0cnoopcripto07 - CentOS5.x - Nodo Pandemia senza <op> ( crypto fs )
0clocal07 - Avvia sistema locale su disco 0
0cmemtest8607 - Test Ram del Sistema


05[F1-Main] [F2-General] [F3-Expert] [F4-Kernel] [F5-Rescue]07
