

                09Welcome to Pandemia Installer!07
0a
                          .-=-.          .--.
              __        .'     '.       /  " )
      _     .'  '.     /   .-.   \     /  .-'0c\0a
     ( \   / .-.  \   /   /   \   \   /  /    0c^0a
      \ `-` /   \  `-'   /     \   `-`  /
       `-.-`     '.____.'       `.____.'  07by 0cRossonet
07

Inserisci il modello di sistema che intendi installare:
( 0aSe con si seleziona niente, dopo 60 secondi, parte
       CentOS5.x - Nodo Pandemia da server remoto VNC007 ) 

0cpandemia07 - CentOS5.x - Nodo Pandemia da server remoto VNC 0
0cpandemia107 - CentOS5.x - Nodo Pandemia da server remoto VNC 1
0cpandemia207 - CentOS5.x - Nodo Pandemia da server remoto VNC 2
0clocale07 - CentOS5.x - Nodo Pandemia da server remoto VNC locale
0cnovnc07 - CentOS5.x - Nodo Pandemia da server remoto console locale
0ccripto07 - CentOS5.x - Nodo Pandemia da server remoto criptofs console locale
0cmemtest8607 - Test Ram del Sistema


05[F1-Main] [F2-General] [F3-Expert] [F4-Kernel] [F5-Rescue]07
